# Generated by Django 3.2.5 on 2021-08-01 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='почта')),
                ('region', models.CharField(max_length=255, verbose_name='регион')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(None, 'не выбрана'), ('первая', 'первая'), ('вторая', 'вторая'), ('третья', 'третья')], max_length=355, null=True, verbose_name='категория')),
                ('role', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(None, 'не выбрана'), ('клиент', 'клиент'), ('исполнитель', 'исполнитель'), ('фирма', 'фирма')], max_length=113, null=True, verbose_name='роль')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='заголовок')),
                ('slug', models.SlugField(blank=True, max_length=355, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(None, 'не выбрана'), ('первая', 'первая'), ('вторая', 'вторая'), ('третья', 'третья')], max_length=355, null=True, verbose_name='категория')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='дата заказа')),
                ('open', models.BooleanField(default=True, verbose_name='открыт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='дата заказа')),
                ('text', models.TextField(verbose_name='текст')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сообшение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='дата заказа')),
                ('text', models.TextField(verbose_name='текст')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.order', verbose_name='заказ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['timestamp'],
            },
        ),
    ]
