# Generated by Django 3.2.5 on 2021-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='подвидвид работ'),
        ),
    ]
