# Generated by Django 3.2.5 on 2021-08-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='subcategory',
            new_name='subcategories',
        ),
    ]
