# Generated by Django 3.2.5 on 2021-09-06 12:37

import core.handlers
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210827_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название')),
                ('logo', models.ImageField(default='unknown.png', upload_to=core.handlers.get_img_upload_path, verbose_name='логотип')),
                ('work_experience', models.CharField(choices=[(None, 'не выбран'), ('3', '3'), ('5', '5'), ('10', '10'), ('более', '> 15')], max_length=5, verbose_name='опыт работ')),
                ('searching_workers', models.BooleanField(default=False, verbose_name='поиск работников')),
                ('categories', models.ManyToManyField(to='services.Category', verbose_name='вид работ')),
                ('subcategories', models.ManyToManyField(to='services.SubCategory', verbose_name='подвид работ')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(None, 'не выбрана'), ('заказчик', 'заказчик'), ('исполнитель', 'исполнитель'), ('фирма', 'фирма')], max_length=25, null=True, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.CharField(choices=[(None, 'не выбран'), ('3', '3'), ('5', '5'), ('10', '10'), ('более', '> 15')], default=1, max_length=5, verbose_name='опыт работы'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ObjectForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category', verbose_name='вид работ')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.firm', verbose_name='фирма')),
            ],
            options={
                'verbose_name': 'Объект на продажу',
                'verbose_name_plural': 'Объукты на продажу',
            },
        ),
    ]
