# Generated by Django 3.2.5 on 2021-09-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20210906_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.firm', verbose_name='фирма'),
        ),
    ]
