# Generated by Django 3.2.5 on 2021-09-06 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_profile_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectforsale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_trips',
            field=models.BooleanField(default=False, verbose_name='командировки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='searching_work',
            field=models.BooleanField(default=False, verbose_name='в поиске работы'),
        ),
    ]
