# Generated by Django 3.2.5 on 2021-09-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20210906_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectforsale',
            options={'verbose_name': 'Объект на продажу', 'verbose_name_plural': 'Объекты на продажу'},
        ),
    ]
